name: Go

on:
  workflow_call:

  push:
    branches-ignore: main
    paths:
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '!.github/**'
      - '!**.bash'

env:
  TELEPORT_HOST: ${{secrets.TELEPORT_HOST}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.CI_PRIVATE_REPOS_GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Environment list
        run: env
      - name: Test
        run: make test
      - name: Build
        run: make build

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws # default is linode
          region: "us-west-1"
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Deploy canary build to S3
        if: github.ref == 'refs/heads/canary'
        run: make BUILD_CANARY=true deploy-canary

      - name: Deploy main build to S3
        if: github.ref == 'refs/heads/main'
        run: make deploy
