name: Go

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    - name: Granting private modules access
      run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    - name: Test
      run: make test
    - name: Build
      run: make build

    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.1
      with:
        provider: aws # default is linode
        region: 'us-west-1'
        access_key: ${{ secrets.S3_ACCESS_KEY }}
        secret_key: ${{ secrets.S3_SECRET_KEY }}

    - name: Deploy canary build to S3
      if: github.ref == 'refs/heads/canary'
      run: make BUILD_CANARY=true deploy-canary

    - name: Deploy main build to S3
      if: github.ref == 'refs/heads/main'
      run: make deploy
