name: docker push
on:
  workflow_dispatch:
  
    push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"

jobs:
  go:
    uses: ./.github/workflows/go.yml
    secrets: inherit
    
  docker_push:
    name: docker push
    needs: [go]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v3"
      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: google-github-actions/auth@v0
        id: google_auth
        with:
          token_format: access_token
          workload_identity_provider: projects/472305719257/locations/global/workloadIdentityPools/github-actions/providers/ghactions-provider
          service_account: ghactions@lantern-cloud.iam.gserviceaccount.com

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.google_auth.outputs.access_token }}

      - name: docker push
        uses: docker/build-push-action@v3
        with:
          secrets: |
            "github_oauth_token=${{ secrets.GH_TOKEN }}"
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            us-docker.pkg.dev/lantern-cloud/containers/http-proxy:${{ github.sha }}
